"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "../../"

"preserve_hierarchy": true

"files": [
  {
    "source": "Sources/Packages/Resources/Localizable.xcstrings",
    "translation": "Sources/Packages/Resources/Localizable.xcstrings",
    "multilingual": true
  }
]
