name: Test

on: [push, pull_request]
jobs:
  test:
    permissions:
        contents: read
    runs-on: xcode-27
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v5
    - name: Test Main Packages
      run: xcrun xcodebuild -project Sources/Secretive.xcodeproj -scheme PackageTests test
      # SPM doesn't seem to pick up on the tests currently?
      # run: swift test --build-system swiftbuild --package-path Sources/Packages
    - name: Test SecretKit Packages
      run: swift test --build-system swiftbuild
